# _config.yml

# Site settings
title: My Love Website
description: You know where is there? It is magic island! enjoy your days!
baseurl: ""  # The base URL of your site (leave empty for GitHub Pages)
url: "https://github.com/What3ver7/rep"  # Replace 'username' with your GitHub username

# Theme settings (you can choose from many pre-built themes in Jekyll)
remote_theme: pages-themes/midnight@v0.2.0
show_downloads: true
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Social links (you can add links to your social profiles)
social_links:
  - name: "Twitter"
    url: "https://github.com/What3ver7/rep"
  - name: "GitHub"
    url: "https://github.com/What3ver7/rep"

# Other settings (you can add more as needed)
markdown: kramdown  # The Markdown processor to use
